build: Updating npm dependencies
* brace-expansion: 1.1.13, 5.0.5 → 1.1.13, 5.0.6
  * https://github.com/advisories/GHSA-jxxr-4gwj-5jf2
* engine.io: 6.6.4 → 6.6.8
  * https://github.com/advisories/GHSA-58qx-3vcg-4xpx
* fast-uri: 3.1.0 → 3.1.2
  * https://github.com/advisories/GHSA-q3j6-qgpj-74h6
  * https://github.com/advisories/GHSA-v39h-62p7-jpjc
* postcss: 8.4.38 → 8.5.15
  * https://github.com/advisories/GHSA-qx2v-qp2m-jg93
* socket.io-adapter: 2.5.5 → 2.5.7
  * https://github.com/advisories/GHSA-58qx-3vcg-4xpx
* tmp: 0.2.5 → 0.2.7
  * https://github.com/advisories/GHSA-ph9p-34f9-6g65
* ws: 8.17.1 → 8.20.1
  * https://github.com/advisories/GHSA-58qx-3vcg-4xpx

To unbreak CI per T430456:
* eslint-config-wikimedia: 0.28.2 → 0.32.4
  This essentially backports I071470f387 (363a0a6516)
  and I030f32ac7 (2b137d74eb)

Additionally unbreak CI per:

```
Warning: Running stylelint failed
TypeError: Cannot read properties of undefined (reading 'B')
   at Module.unpackFeature (/src/node_modules/caniuse-lite/dist/unpacker/feature.js:60:29)
```

which appears to be due to an outdated version of stylelint-no-unsupported-browser-features
per https://github.com/browserslist/caniuse-lite/issues/129 and was
fixed in stylelint-config-wikimedia 0.19 which in turn requires
grunt-stylelint 0.21.
* grunt-stylelint: 0.20.1 → 0.21.0
* stylelint-config-wikimedia: 0.17.2 → 0.19.1
* stylelint-no-unsupported-browser-features: 8.0.2 → 8.1.1

This also backports I7c6bd6fd0 (b54d928144) and Ib88e3060b1 (af744d6c06)
to address minor stylelint changes.

Bug: T430456
Change-Id: I9b204d44b9e33a135afe09a0649790e89027ce81